In [1]:
from __future__ import print_function
import torch

In [14]:
x = torch.empty(5,3)
print(x)
print(x.size())

tensor([[-5.7531e+13,  4.5750e-41, -9.8850e+29],
        [ 3.0767e-41,         nan,  3.0767e-41],
        [-4.6747e+29,  3.0767e-41, -7.0845e+29],
        [ 3.0767e-41, -1.5960e-21,  4.5750e-41],
        [ 7.0975e+22,  1.3032e-43,  0.0000e+00]])
torch.Size([5, 3])


In [15]:
x = torch.rand(5,3)
print(x)

tensor([[0.2776, 0.7234, 0.7913],
        [0.9168, 0.2705, 0.0890],
        [0.3529, 0.3989, 0.4785],
        [0.4502, 0.4564, 0.8897],
        [0.9936, 0.6153, 0.8071]])


In [16]:
x = torch.zeros(5,3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [20]:
x = torch.tensor([5,3.0])
print(x)
print(x.size())
print(x.dtype)

x = torch.tensor([5,3])
print(x.dtype)

x = torch.tensor([[5,3.0], [1,10]])
print(x)
print(x.size())

tensor([5., 3.])
torch.Size([2])
torch.float32
torch.int64
tensor([[ 5.,  3.],
        [ 1., 10.]])
torch.Size([2, 2])


In [23]:
x = x.new_ones(5,3, dtype = torch.double)
print(x)
print(x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
torch.Size([5, 3])


In [25]:
x = torch.randn_like(x, dtype = torch.float)
print(x)
print(x.size())

tensor([[ 0.1732, -0.8274, -2.4235],
        [-0.7682, -0.4011,  0.9669],
        [ 0.0228, -2.5244,  1.5456],
        [-1.8021,  0.9679,  1.2593],
        [-0.9379,  0.9101,  1.4505]])
torch.Size([5, 3])


In [28]:
x = torch.zeros(5,3, dtype = torch.float)
print(x)

y = torch.ones(5,3, dtype = torch.float)
print(y)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [31]:
print(x+y)
print(torch.add(x,y))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [32]:
result = torch.empty(5,4)
print(result)
torch.add(x,y, out = result)
print(result)

tensor([[-57530986266624.0000,               0.0000, -57530986266624.0000,
                       0.0000],
        [              0.0000,               0.0000,               0.0000,
                       0.0000],
        [              0.0000,               0.0000,               0.0000,
                       0.0000],
        [              0.0000,               0.0000,               0.0000,
                       0.0000],
        [              0.0000,               0.0000,               0.0000,
                       0.0000]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [33]:
y.add_(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [37]:
x = torch.rand(5,3, dtype = torch.float)
print(x)
print(x[:,0])

tensor([[0.0036, 0.7475, 0.3885],
        [0.8120, 0.5376, 0.9757],
        [0.0096, 0.7371, 0.0019],
        [0.7561, 0.3707, 0.1151],
        [0.5693, 0.4592, 0.9710]])
tensor([0.0036, 0.8120, 0.0096, 0.7561, 0.5693])


In [40]:
x = torch.rand(4,4, dtype = torch.float)
print(x)

y = x.view(16)
z = y.view(-1,8)
print(y, y.size())
print(z, z.size())

tensor([[0.1458, 0.3197, 0.2166, 0.6038],
        [0.0491, 0.9108, 0.9572, 0.6632],
        [0.2659, 0.7804, 0.3550, 0.5593],
        [0.7949, 0.9113, 0.6463, 0.6886]])
tensor([0.1458, 0.3197, 0.2166, 0.6038, 0.0491, 0.9108, 0.9572, 0.6632, 0.2659,
        0.7804, 0.3550, 0.5593, 0.7949, 0.9113, 0.6463, 0.6886]) torch.Size([16])
tensor([[0.1458, 0.3197, 0.2166, 0.6038, 0.0491, 0.9108, 0.9572, 0.6632],
        [0.2659, 0.7804, 0.3550, 0.5593, 0.7949, 0.9113, 0.6463, 0.6886]]) torch.Size([2, 8])


In [41]:
a = torch.ones(5)
print(a, type(a))
b = a.numpy()
print(b, type(b))

tensor([1., 1., 1., 1., 1.]) <class 'torch.Tensor'>
[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>


In [42]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [43]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a, type(a))
print(b, type(b))

[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>
tensor([1., 1., 1., 1., 1.], dtype=torch.float64) <class 'torch.Tensor'>


In [45]:
torch.cuda.is_available()

True

In [46]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x, device = device)
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to('cpu', torch.double))
    c = z.to('cpu', torch.double)

tensor([[1.1458, 1.3197, 1.2166, 1.6038],
        [1.0491, 1.9108, 1.9572, 1.6632],
        [1.2659, 1.7804, 1.3550, 1.5593],
        [1.7949, 1.9113, 1.6463, 1.6886]], device='cuda:0')
tensor([[1.1458, 1.3197, 1.2166, 1.6038],
        [1.0491, 1.9108, 1.9572, 1.6632],
        [1.2659, 1.7804, 1.3550, 1.5593],
        [1.7949, 1.9113, 1.6463, 1.6886]], dtype=torch.float64)


In [47]:
print(x.device, y.device, z.device, c.device)

cuda:0 cuda:0 cuda:0 cpu


In [48]:
x.size()

torch.Size([4, 4])